sudo: required
services:
  - docker

before_install:
  - docker build -t ranbatrekker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ranbatrekker/docker-react npm run test  -- --coverage
